import Head from 'next/head';
import React from 'react';
import style from '../styles/About.module.scss';

const About = () => {
  return (
    <div className="container">
      <Head>
        <title>Styled Shop | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="aboutPage">
        <h1>About</h1>
      </div>
    </div>
  );
}

export default About;