import Head from 'next/head';
import { useQuery } from 'urql';
import { PRODUCT_QUERY } from '../lib/query';
import styles from '../styles/Home.module.scss';

export default function Home() {
  //FETCH PRODUCTS
  const [results] = useQuery({query: PRODUCT_QUERY});
  const { data, fetching, error } = results;

  //Check for the data coming in
  if(fetching) return <p>Loading...</p> 
  if(error) return <p>Oops, something wrong...</p> 

  return (
    <div className='page'>
      <Head>
        <title>Styled Shop | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container'>
        <h1>Hello Next</h1>
      </div>
    </div>
  )
}


